[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"

anyhow = "1.0.86"
time = "0.3.36"

axum = { version = "0.7.5", features = ["tokio", "ws"] }
lettre = { version = "0.11.7", features = ["tokio1-native-tls"] }
tracing-subscriber = { version = "0.3.18", features = ["time"] }
tracing = "0.1.40"

dashmap = "6.0.1"
sqlx = "0.8.1"