//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "chat", table_name = "assoc_room_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub room_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub iden_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::lone_role_info::Entity",
        from = "(Column::IdenId, Column::IdenId, Column::IdenId, Column::IdenId)",
        to = "(super::lone_role_info::Column::Id, super::lone_role_info::Column::Id, super::lone_role_info::Column::Id, super::lone_role_info::Column::Id)",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    LoneRoleInfo,
    #[sea_orm(
        belongs_to = "super::room_info::Entity",
        from = "Column::RoomId",
        to = "super::room_info::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    RoomInfo,
    #[sea_orm(
        belongs_to = "super::user_info::Entity",
        from = "Column::UserId",
        to = "super::user_info::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserInfo,
}

impl Related<super::lone_role_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoneRoleInfo.def()
    }
}

impl Related<super::room_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoomInfo.def()
    }
}

impl Related<super::user_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
