//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "chat", table_name = "lone_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub owner_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assoc_lone_user::Entity")]
    AssocLoneUser,
    #[sea_orm(has_many = "super::lone_role_info::Entity")]
    LoneRoleInfo,
    #[sea_orm(has_many = "super::room_info::Entity")]
    RoomInfo,
    #[sea_orm(
        belongs_to = "super::user_info::Entity",
        from = "Column::OwnerId",
        to = "super::user_info::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserInfo,
}

impl Related<super::assoc_lone_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssocLoneUser.def()
    }
}

impl Related<super::lone_role_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoneRoleInfo.def()
    }
}

impl Related<super::room_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoomInfo.def()
    }
}

impl Related<super::user_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
