//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "chat", table_name = "lone_role_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub lone_id: i32,
    pub privilege: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assoc_lone_user::Entity")]
    AssocLoneUser,
    #[sea_orm(has_many = "super::assoc_room_user::Entity")]
    AssocRoomUser,
    #[sea_orm(
        belongs_to = "super::lone_info::Entity",
        from = "Column::LoneId",
        to = "super::lone_info::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    LoneInfo,
}

impl Related<super::assoc_lone_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssocLoneUser.def()
    }
}

impl Related<super::assoc_room_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssocRoomUser.def()
    }
}

impl Related<super::lone_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoneInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
