//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "chat", table_name = "room_identity_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub room_id: i32,
    pub privilege: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::room_info::Entity",
        from = "Column::RoomId",
        to = "super::room_info::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    RoomInfo,
}

impl Related<super::room_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoomInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
